### ISSUE TITLE
lib4moocdata/coursera/bin/populate_sqlite_db.pl

### ISSUE THREAD

**Issue by knmnyn** [cmkumar87/lib4moocdata#4]
Add version info so that different legacy versions of the coursera dumps can be ingested properly.
Prompted by U Pitt Disaster Prep iteration 1 data.

**Comment by cmkumar87** [comment]
This has been fixed and tested. populate_sqlite_db.pl script will now accept an option named version.
We also found a 3rd version of the schema which remains to be fixed.

**Comment by cmkumar87** [comment]
The 3rd version only differs slightly. This does not require any additional code change.
